package com.exception;

public class ArithmeticTryCatchMain {
	public static void main(String[] args) {
		ArithmeticTryCatch a1=new ArithmeticTryCatch();
		System.out.println("in main");
		a1.method4();
	} 

}
